name: 'Notify Slack on Release'
description: 'Notify a Slack channel when there is a new release'
branding:
  icon: 'book'
  color: 'green'
author: 'Instantish'
inputs:
  slack_webhook_url: # change this
    required: true
    description: 'The webhook URL for the Slack channel'
runs:
  using: 'node16'
  main: 'dist/index.js'
